# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
warp_mc_R <- function(s, b, w) {
    .Call(`_wispack_warp_mc_R`, s, b, w)
}

#' @export
sigmoid_stable_R <- function(x) {
    .Call(`_wispack_sigmoid_stable_R`, x)
}

#' @export
poly_sigmoid_R <- function(b, deg, Rt, tslope, tpoint) {
    .Call(`_wispack_poly_sigmoid_R`, b, deg, Rt, tslope, tpoint)
}

